version: '3'

services:
    app:
        image: silarhi/php-apache:7.4
        ports:
            - 8081:80
        volumes:
            - ./php:/app:ro

    varnish:
        image: varnish:6.3
        command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-t" , "0"]
        ports:
            - 8080:80
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
