version: '3'

services:
    app:
        image: guystlr/php-apache:7.2
        container_name: lab_php_app
        labels:
            - "traefik.frontend.rule=Host:labs.sainthillier.fr;PathPrefixStrip:/php,/_errors;PathPrefix:/php"
        restart: always
        networks:
            - web

networks:
    web:
        external: true
